{{- if and .Values.rollout.enabled (eq .Values.rollout.strategy "blueGreen") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-info-service.fullname" . }}-preview
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
    role: preview
spec:
  type: {{ .Values.rollout.blueGreen.previewService.type | default "ClusterIP" }}
  selector:
    {{- include "devops-info-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq (.Values.rollout.blueGreen.previewService.type | default "ClusterIP") "NodePort") .Values.rollout.blueGreen.previewService.nodePort }}
      nodePort: {{ .Values.rollout.blueGreen.previewService.nodePort }}
      {{- end }}
{{- end }}
