---
app_name: devops-python
docker_image: mituta/devops-info-service-python
docker_tag: latest
app_port: 8000
app_internal_port: 5000
compose_project_dir: "/opt/{{ app_name }}"
app_env:
  HOST: "0.0.0.0"
  PORT: "5000"
