replicaCount: 3

image:
  repository: mituta/devops-info-service
  tag: "lab12"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

env:
  - name: PORT
    value: "5000"
  - name: APP_RELEASE
    value: "v1"

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

rollout:
  enabled: false
  strategy: canary
  canary:
    steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause:
          duration: 30s
      - setWeight: 60
      - pause:
          duration: 30s
      - setWeight: 80
      - pause:
          duration: 30s
      - setWeight: 100
  blueGreen:
    autoPromotionEnabled: false
    autoPromotionSeconds: 0
    scaleDownDelaySeconds: 30
    previewService:
      type: ClusterIP
      nodePort: null
  analysis:
    enabled: false
    interval: 10s
    count: 3
    failureLimit: 1

podAnnotations: {}
podLabels: {}

serviceAccount:
  create: false
  name: ""

autoscaling:
  enabled: false

secrets:
  DATABASE_USERNAME: "admin"
  DATABASE_PASSWORD: "changeme"

vault:
  enabled: false
  role: "devops-info-service"
  secretPath: "secret/data/devops-info-service/config"

environment: "production"
logLevel: "info"

persistence:
  enabled: true
  size: 100Mi
  storageClass: ""
