replicaCount: 2

image:
  tag: "lab02"

env:
  - name: PORT
    value: "5000"
  - name: APP_RELEASE
    value: "dev"

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30081

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 3
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
