replicaCount: 5

image:
  tag: "lab02"

env:
  - name: PORT
    value: "5000"
  - name: APP_RELEASE
    value: "canary-v1"

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30090

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

persistence:
  enabled: false

rollout:
  enabled: true
  strategy: canary
  canary:
    steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause:
          duration: 30s
      - setWeight: 60
      - pause:
          duration: 30s
      - setWeight: 80
      - pause:
          duration: 30s
      - setWeight: 100
