replicaCount: 2

image:
  repository: mituta/devops-info-service
  tag: "lab02"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

env:
  - name: PORT
    value: "5000"
  - name: APP_RELEASE
    value: "v2"

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

podAnnotations: {}
podLabels: {}
